### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by hacdias** [vuejs-templates/pwa#64] opened 2017-07-31 10:53 UTC
Just followed this instructions:

```
$ npm install -g vue-cli
$ vue init pwa my-project
$ cd my-project
$ npm install
$ npm run dev
```

Error:

```
Html Webpack Plugin:
  TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
  
  - 1:5 eval
    webpack-internal:///1:5:27
  
  - 1:20 module.exports
    webpack-internal:///1:20:3
  
  - index.js:264 
    [test]/[html-webpack-plugin]/index.js:264:16
  
  - From previous event:
  
  - index.js:252 HtmlWebpackPlugin.executeTemplate
    [test]/[html-webpack-plugin]/index.js:252:6
  
  - index.js:137 
    [test]/[html-webpack-plugin]/index.js:137:18
  
  - From previous event:
  
  - index.js:132 Compiler.
    [test]/[html-webpack-plugin]/index.js:132:8
  
  - Tapable.js:188 Compiler.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:188:13
  
  - Compiler.js:308 Compiler.emitAssets
    [test]/[webpack]/lib/Compiler.js:308:7
  
  - Compiler.js:52 onCompiled
    [test]/[webpack]/lib/Compiler.js:52:18
  
  - Compiler.js:499 
    [test]/[webpack]/lib/Compiler.js:499:13
  
  - Tapable.js:184 next
    [test]/[tapable]/lib/Tapable.js:184:11
  
  - CachePlugin.js:62 Compiler.
    [test]/[webpack]/lib/CachePlugin.js:62:5
  
  - Tapable.js:188 Compiler.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:188:13
  
  - Compiler.js:496 
    [test]/[webpack]/lib/Compiler.js:496:10
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:649 self.applyPluginsAsync.err
    [test]/[webpack]/lib/Compilation.js:649:19
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:640 self.applyPluginsAsync.err
    [test]/[webpack]/lib/Compilation.js:640:11
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:635 self.applyPluginsAsync.err
    [test]/[webpack]/lib/Compilation.js:635:10
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:631 sealPart2
    [test]/[webpack]/lib/Compilation.js:631:9
  
  - Tapable.js:177 Compilation.applyPluginsAsyncSeries
    [test]/[tapable]/lib/Tapable.js:177:46
  
  - Compilation.js:579 Compilation.seal
    [test]/[webpack]/lib/Compilation.js:579:8

```

It works if I remove this section from index.html:

```
<% for (var chunk of webpack.chunks) {
        for (var file of chunk.files) {
          if (file.match(/\.(js|css)$/)) { %>
    <link rel="<%= chunk.initial?'preload':'prefetch' %>" href="<%= htmlWebpackPlugin.files.publicPath + file %>" as="<%= file.match(/\.css$/)?'style':'script' %>"><% }}} %>
  
```

**Comment by fabionolasco** [comment] 2017-07-31 14:00
Thank you for the fix! But I was wondering if you have idea on when it will be accessible through the installation process?

**Comment by hacdias** [comment] 2017-07-31 14:04
No problem 😄 IDK. Only when one of the contributors of this repository merges #65

**Comment by addyosmani** [comment] 2017-08-09 16:50
I just tested trying to reproduce this issue with the version in master and was unable to get the same errors during `npm run dev` (this was on a fresh machine).

Could you try git cloning this repository and trying:

```
vue init ~/path/to/cloned/repo
npm install
npm run dev
```

and let me know if this is still an issue? @hacdias thanks for the PR in #64. If you could also verify whether the above steps don't address this for you, I can chase down what else might be required to repro.

**Comment by hacdias** [comment] 2017-08-09 17:11
Hey @addyosmani! Oddly enough, I didn't receive any error now. It could've been some sort of problem on my machine, but @fabionolasco had the same issue. Have no ideia what it was. Although I can say that the problem appeared from one moment to another: it was working the day before I filed this issue.

**Comment by jeffposnick** [comment] 2017-11-14 15:57
The current configuration works out of the box for me, and furthermore, when I switch to using `webpack.compilation.chunks` as per #65, it no longer works, since `webpack.compilation` doesn't exist.

As per https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates, `html-webpack-plugin` will pass in a variable called `webpack` to the HTML template, and that corresponds to a `stats` object.

As per https://webpack.js.org/api/stats/#chunk-objects, a `stats` object has a property called `chunks`, which is an array of `chunk` objects.

So the usage in the current `index.html` follows the documented API for the current versions of webpack and `html-webpack-plugin`.

I'm going to close this issue, but if you do have steps to reproduce (perhaps due to using older versions of one of the dependencies?) please re-open.

**Closed by jeffposnick** 2017-11-14 15:57 UTC
Labels: needs-more-info
